# ANN- SLEEP HEALTH DATASET(REGRESSION)

In [11]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [12]:
df=pd.read_csv("C:/Users/mohan/Downloads/Sleep_Health_and_Lifestyle_Dataset.csv")
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Occupation']=le.fit_transform(df['Occupation'])
df['BMI Category']=le.fit_transform(df['BMI Category'])
df['Sleep Disorder']=le.fit_transform(df['Sleep Disorder'])

In [14]:
df=df.drop(columns='Person ID',axis=1)
df=df.drop(columns='Occupation',axis=1)
df=df.drop(columns='Blood Pressure',axis=1)
df=df.drop(columns='Heart Rate',axis=1)
df=df.drop(columns='Daily Steps',axis=1)
df=df.drop(columns='Sleep Disorder',axis=1)

In [15]:
df

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category
0,1,27,6.1,6,42,6,3
1,1,28,6.2,6,60,8,0
2,1,28,6.2,6,60,8,0
3,1,28,5.9,4,30,8,2
4,1,28,5.9,4,30,8,2
...,...,...,...,...,...,...,...
369,0,59,8.1,9,75,3,3
370,0,59,8.0,9,75,3,3
371,0,59,8.1,9,75,3,3
372,0,59,8.1,9,75,3,3
373,0,59,8.1,9,75,3,3

In [16]:
y=df["Quality of Sleep"]
y

0      6
1      6
2      6
3      4
4      4
      ..
369    9
370    9
371    9
372    9
373    9
Name: Quality of Sleep, Length: 374, dtype: int64

In [17]:
x=df.drop(columns='Quality of Sleep',axis=1)
x

,Gender,Age,Sleep Duration,Physical Activity Level,Stress Level,BMI Category
0,1,27,6.1,42,6,3
1,1,28,6.2,60,8,0
2,1,28,6.2,60,8,0
3,1,28,5.9,30,8,2
4,1,28,5.9,30,8,2
...,...,...,...,...,...,...
369,0,59,8.1,75,3,3
370,0,59,8.0,75,3,3
371,0,59,8.1,75,3,3
372,0,59,8.1,75,3,3
373,0,59,8.1,75,3,3

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scale = scaler.fit_transform(x_train)
x_test_scale = scaler.transform(x_test)

In [21]:
from tensorflow import keras

# Check number of input features
print(x_train.shape)
print(y_train.shape)

model = keras.Sequential([
    keras.layers.Input(shape=(x_train.shape[1],)),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(50, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(1)  # Single output for regression
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

history = model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)

(299, 6)
(299,)
Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 5s 95ms/step - loss: 10.0496 - mae: 2.5407 - val_loss: 2.0876 - val_mae: 1.2039
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 2.8279 - mae: 1.3284 - val_loss: 2.4728 - val_mae: 1.3407
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 2.0919 - mae: 1.2357 - val_loss: 1.4145 - val_mae: 1.0462
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1.4442 - mae: 0.9858 - val_loss: 0.9759 - val_mae: 0.8006
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1.2909 - mae: 0.9080 - val_loss: 0.8783 - val_mae: 0.8013
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1.0632 - mae: 0.8183 - val_loss: 1.0062 - val_mae: 0.7832
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.8932 - mae: 0.7772 - val_loss: 0.5913 - val_mae: 0.6441
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.8207 - mae: 0.7310 - val_loss: 0.6228 - val_mae: 0.6485
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.7143 - mae: 0.6849 - val_loss: 0.4607 - val_mae: 0.5759
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5801 - mae: 0.6170 - val_loss: 0.4202 - val_mae: 0.5152
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.4561 - mae: 0.5524 - val_loss: 0.3443 - val_mae: 0.4722
Epoch 12/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.4119 - mae: 0.5181 - val_loss: 0.4395 - val_mae: 0.5383
Epoch 13/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.4372 - mae: 0.5255 - val_loss: 0.4973 - val_mae: 0.5726
Epoch 14/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.3671 - mae: 0.4810 - val_loss: 0.2852 - val_mae: 0.4072
Epoch 15/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.2696 - mae: 0.4135 - val_loss: 0.2405 - val_mae: 0.3650
Epoch 16/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.2787 - mae: 0.3982 - val_loss: 0.2034 - val_mae: 0.3337
Epoch 17/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2790 - mae: 0.4123 - val_loss: 0.2070 - val_mae: 0.3256
Epoch 18/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2182 - mae: 0.3620 - val_loss: 0.2069 - val_mae: 0.3241
Epoch 19/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.2081 - mae: 0.3451 - val_loss: 0.1973 - val_mae: 0.3074
Epoch 20/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2083 - mae: 0.3413 - val_loss: 0.2327 - val_mae: 0.3517

In [22]:
train_loss, train_accuracy = model.evaluate(x_train, y_train, verbose=0)
test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=0)

print("Training Accuracy :", round(train_accuracy * 100, 2), "%")
print("Testing Accuracy  :", round(test_accuracy * 100, 2), "%")

Training Accuracy : 34.64 %
Testing Accuracy  : 29.83 %